/******************************************************
 * This is the main file for the mips1 ArchC model    *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 
// Rodolfo editou aqui
//
const char *project_name="mips";
const char *project_file="mips1.ac";
const char *archc_version="2.0beta1";
const char *archc_options="-abi -dy ";

#include <systemc.h>
#include "mips.H"
#include "memory.h"
#include "bus.h"


int sc_main(int ac, char *av[]) {
  //!  ISA simulator
  mips mips_proc1("mips");
  mips mips_proc2("mips_2");
  //! Bus
  ac_tlm_bus bus("bus");
  // Memory
  ac_tlm_mem mem("mem");

#ifdef AC_DEBUG
  ac_trace("mips1_proc1.trace");
#endif 

  mips_proc1.DM_port(bus.target_export);
  mips_proc2.DM_port(bus.target_export);
  bus.MEM_port(mem.target_export);

  int ac_aux = ac;
  char av_aux[2][100];
  strcpy(av_aux[0], av[0]);
  strcpy(av_aux[1], av[1]);

  mips_proc1.init(ac, av);

  ac = ac_aux; 
  strcpy(av[0], av_aux[0]);
  strcpy(av[1], av_aux[1]);
  printf("%s %s\n", av[0], av[1]);
  mips_proc2.init(ac, av);
  cerr << endl;

  sc_start();
  // mips_proc2.mips_isa.PauseProcessor();

  mips_proc1.PrintStat();
  mips_proc2.PrintStat();
  cerr << endl;

#ifdef AC_STATS
  mips1_proc1.ac_sim_stats.time = sc_simulation_time();
  mips1_proc1.ac_sim_stats.print();
  mips1_proc2.ac_sim_stats.time = sc_simulation_time();
  mips1_proc2.ac_sim_stats.print();
#endif 

#ifdef AC_DEBUG
  ac_close_trace();
#endif 

  return mips_proc1.ac_exit_status;
}
